services:
  test-db:
    image: postgres:15
    container_name: test-db-schedule
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    networks:
      - testnet

  schedule-service:
    build:
      context: .
    container_name: test-schedule
    command: ["pytest", "-v", "/app/tests"]
    depends_on:
      test-db:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - testnet

networks:
  testnet:
    driver: bridge

