name: Build Dev and Trigger Deploy
on:
  push:
    branches: [ develop ]

permissions:
  id-token: write 
  contents: read  

jobs:
  build-services:
    name: Build git Service - ${{ matrix.service_name }}
    uses: ./.github/workflows/reusable-service-build.yml
    strategy:
      fail-fast: false
      matrix:
        service_name: [auth, booking, schedule]
    with:
      environment: dev
      service_name: ${{ matrix.service_name }}
      image_tag: ${{ github.sha }}
    secrets: inherit 

  build-frontend:
    name: Build Frontend
    uses: ./.github/workflows/reusable-frontend-cd.yml
    with:
      environment: dev
    secrets: inherit

  trigger-deployment:
    name: Trigger Infrastructure Deploy
    needs: [build-services, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow in infra repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TERRAFORM_REPO_PAT }}
          repository: ${{ vars.TERRAFORM_REPO_NAME }} 
          event-type: deploy-dev 
          client-payload: '{"sha": "${{ github.sha }}"}'