# .github/workflows/cd-frontend-prod.yml

name: Frontend CD (Prod)

on:
  push:
    tags: [ 'v*.*.*' ] 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Build & Deploy to Prod
    uses: ./.github/workflows/reusable-frontend-ci-cd.yml
    with:
      environment: prod
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_FRONTEND_ROLE }}