# .github/workflows/cd-frontend-dev.yml

name: Frontend CD (Dev)

on:
  push:
    branches: [ develop ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Build & Deploy to Dev
    uses: ./.github/workflows/reusable-frontend-ci-cd.yml
    with:
      environment: dev
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_FRONTEND_ROLE }}