# .github/workflows/cd-frontend-prod.yml

name: Frontend CD (Prod)

on:
  push:
    tags: [ 'v*.*.*' ] 
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Build & Deploy to Prod
    uses: ./.github/workflows/reusable/frontend-ci-cd.yml
    with:
      environment: prod
    secrets: inherit 