name: Integration Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Install test dependencies
        run: |
          pip install pytest httpx pytest-asyncio

      - name: Run integration tests
        run: PYTHONPATH=. pytest tests/integration

      - name: Shut down docker-compose
        if: always()
        run: docker compose -f docker-compose.test.yml down
