name: Linting and Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint 
          pip install -r services/auth/requirements.txt
          pip install -r services/booking/requirements.txt
          pip install -r services/schedule/requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  unit-tests:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/unit/requirements.txt
          pip install -r services/auth/requirements.txt
          pip install -r services/booking/requirements.txt
          pip install -r services/schedule/requirements.txt

      - name: Run unit tests with coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          JWT_SECRET: your-super-secret-jwt-key-here-make-it-at-least-32-characters-long
          JWT_ALGORITHM: HS256
          SCHEDULE_SERVICE_URL: http://localhost:8000
          AUTH_SERVICE_URL: http://localhost:8000

        run: |
          PYTHONPATH=. python -m pytest tests/unit/ -v --cov-report=html:htmlcov
