name: Linting

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint 
          pip install -r services/auth/requirements.txt
          pip install -r services/booking/requirements.txt
          pip install -r services/schedule/requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
