name: Lint and Unit Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint 
          pip install -r services/auth/requirements.txt
          pip install -r services/booking/requirements.txt
          pip install -r services/schedule/requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  unit-tests-auth:
    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: auth
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r services/auth/requirements.txt
          pip install pytest

      - name: Run auth unit tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/auth
          JWT_SECRET: testsecret
          JWT_ALGORITHM: HS256
        run: |
          PYTHONPATH=. pytest tests/auth

  unit-tests-schedule:
    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: schedule
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r services/schedule/requirements.txt
          pip install pytest

      - name: Run schedule unit tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/schedule
          JWT_SECRET: testsecret
          JWT_ALGORITHM: HS256
        run: |
          PYTHONPATH=. pytest tests/schedule
